version: '3.7'
services:
  broker:
    build: broker
    ports:
      - "8083:8083"
    depends_on:
      - auldfellas
      - dodgygeezers
      - girlsallowed

  auldfellas:
    build: auldfellas
    ports:
      - "8080:8080"

  dodgygeezers:
    build: dodgygeezers
    ports:
      - "8082:8082"

  girlsallowed:
    build: girlsallowed
    ports:
      - "8081:8081"